DR-2054: store per-snapshot catalog metadata
DataBiosphere/jade-data-repo pull request #1052
Opened 2021-09-08 21:08 UTC by pshapiro4broad

Add a new database object with its own DAO to store a json metadata blob that's linked to a snapshot.

2021-09-09 14:33 UTC, fboulnois approved these changes
This looks great. The DB operations are clean and the tests are concise but thorough.

2021-09-09 22:02 UTC, tcjiang9 commented on src/test/java/bio/terra/service/search/SnapshotSearchMetadataDaoTest.java
> +@Category(Connected.class)
Do we actually need connected tests here? Can we not test the same thing with unit tests that verify jdbcTemplate.update is called with the correct params, and trust the underlying db does what it's supposed to. If we want to verify whether we can connect to the database, monitors and metrics should tell us that.

2021-09-09 22:04 UTC, tcjiang9 requested changes
I don't see the value of connected tests, I've been actively trying to remove them, can we not test the same thing with unit tests that verify jdbcTemplate.update is called with the correct params, and trust the underlying db does what it's supposed to? If we want to verify whether we can connect to the database, monitors and metrics should tell us that.

2021-09-10 14:00 UTC, pshapiro4broad commented
> I don't see the value of connected tests, I've been actively trying to remove them, can we not test the same thing with unit tests that verify jdbcTemplate.update is called with the correct params, and trust the underlying db does what it's supposed to? If we want to verify whether we can connect to the database, monitors and metrics should tell us that.

In many cases I'd agree, we want to be careful and not add any more connected tests unless it's necessary. In this case I believe it is necessary, because there's no other way to verify that the liquibase change is correct, and that the SQL commands in string literals are correct. If we used an ORM library, or some other system that auto-generated database tables and DAO bindings from our code, then I can see how having these tests wouldn't be useful.

I do think that any other test that relies on this class wouldn't need to be connected, and could use a mocked version of the DAO class.

2021-09-10 15:57 UTC, pshapiro4broad commented
If there's a concern of the tests affecting our build times, all four tests take less than 2s when I run them locally.

2021-09-10 19:18 UTC, myessail approved these changes

2021-09-13 16:28 UTC, tcjiang9 approved these changes

2021-09-13 17:00 UTC, merged