Add script for 1000 Genomes, fix HCA bug
DataBiosphere/jade-data-repo pull request #1087
Opened 2021-10-11 23:02 UTC by tcjiang9

For now, just look at how the TIM object gets generated, the rest needs to be refactored

2021-10-12 12:55 UTC, fboulnois requested changes
A few suggestions:

2021-10-12 12:55 UTC, fboulnois commented on ops/search/1000Genomes/snapshot.py
> +#!/usr/bin/env python
Perhaps rename the python script to something more descriptive?

2021-10-12 12:55 UTC, fboulnois commented on ops/search/1000Genomes/snapshot.py
> +import json, os, re, uuid
Run `black` on all the *.py files.

2021-10-12 12:55 UTC, fboulnois commented on ops/search/hca/create-hca-collection.py
> +    return publications
Nice catch.

2021-10-12 12:55 UTC, fboulnois commented on ops/search/hca/create-hca-collection.py
> +    print(snapshot)
We should probably remove both print statements actually.

2021-10-12 12:55 UTC, fboulnois commented on ops/search/1000Genomes/snapshot.py
> +    req.add_header(auth, token)
The headers can be added all at once as I found out. Check out lines 94-100.

2021-10-12 12:55 UTC, fboulnois commented on ops/search/1000Genomes/snapshot.py
> +thousand_genomes_search_snapshot_id = "77f1365e-b88d-48e2-a9ab-88ccd6cec68e"
Maybe use `format` here?

2021-10-12 12:55 UTC, fboulnois commented on ops/search/hca/extract-hca-projects.py
> +#todo: refactor to use request library
I've gone back and forth on using the request library.

2021-10-12 18:00 UTC, fboulnois commented on ops/search/1000Genomes/snapshot.py
> +            "dct:modified": now(),
This should probably correspond to the when the snapshot was created and modified.

2021-10-12 18:00 UTC, fboulnois commented on ops/search/1000Genomes/snapshot.py
> +            "dct:description": "",
This should probably have a valid title and description to appear correctly in the catalog.

2021-10-13 20:23 UTC, tcjiang9 commented on ops/search/1000Genomes/snapshot.py
> +            "dct:description": "",
I'm not able to find one, since they come from the project in HCA

2021-10-14 13:14 UTC, fboulnois commented on ops/search/1000Genomes/upsert-metadata.py
> +        ],
One additional comment. We probably want to keep this as `[]` or find the "real" original publication, as usually scientists will look at original publication to figure out whether the data is interesting.

2021-10-20 19:27 UTC, fboulnois requested changes

2021-10-20 19:27 UTC, fboulnois commented on README.md
> +______
?

2021-10-20 19:27 UTC, fboulnois commented on ops/search/1000Genomes/upsert-metadata.py
> +
Need to run `black` on this file.

2021-10-20 19:39 UTC, tcjiang9 commented on README.md
> +______
huh no idea where that came from

2021-10-26 19:50 UTC, fboulnois approved these changes

2021-12-10 18:39 UTC, pshapiro4broad approved these changes

2021-12-10 18:39 UTC, pshapiro4broad commented on ops/search/1000Genomes/upsert-metadata.py
> +       #     raise err
Please remove commented out code before merging up.

2021-12-13 18:58 UTC, merged