DR-2193 soft delete without scratch file
DataBiosphere/jade-data-repo pull request #1161
Opened 2021-12-10 23:01 UTC by tlangs

Adding the ability to provide a List of UUIDs to the data deletion endpoint. This enables users to simply send a request to TDR for soft-deletes, instead of needing to stage a file with the rowIds to be deleted.

2021-12-13 17:03 UTC, nmalfroy requested changes
Looks good! I think the validator thing is the one thing to update

2021-12-13 17:03 UTC, nmalfroy commented on src/main/java/bio/terra/app/controller/DatasetsApiController.java
> +  private void validateDataDeletionRequest(DataDeletionRequest dataDeletionRequest) {
Probably makes sense to have a unit test for this logic

2021-12-13 17:03 UTC, nmalfroy commented on src/main/java/bio/terra/app/controller/DatasetsApiController.java
> +  private void validateDataDeletionRequest(DataDeletionRequest dataDeletionRequest) {
Also, I this logic should live in a validator class (see `DataDeletionRequestValidator` for example)

2021-12-13 17:03 UTC, nmalfroy commented on src/main/java/bio/terra/service/dataset/flight/datadelete/DataDeletionCopyFilesToBigQueryScratchBucketStep.java
> +    } else {
Should be explicitly checking for `JSONARRAY` and then throw with an unrecognized value

2021-12-13 20:53 UTC, samanehsan commented
Since we have the rowIds in the request, could we insert directly into the soft delete table? Or is there a reason we still want to use external tables?

2021-12-13 20:55 UTC, tlangs commented
The external table makes sure the rowIds are valid ids that appear in the dataset table. Plus, it allows for bulk-load operations rather than needing to batch API calls. Its also easy to funnel the JSON array into the same code path as GCS files and not need to maintain two distinct operations for soft-delete.

2021-12-13 21:02 UTC, samanehsan approved these changes
Thanks for the explanation! This lgtm ⛄

2021-12-14 21:44 UTC, nmalfroy approved these changes
Awesome!  Thanks for humoring me :). Also, at some point we should bump to junit 5...I think it simplifies some of the data provider stuff

2021-12-15 17:54 UTC, merged