Fix all LoggerFactory uses to use the .class interface instead of text strings
DataBiosphere/jade-data-repo pull request #1179
Opened 2022-01-04 17:50 UTC by myessail

2022-01-04 17:56 UTC, nmalfroy requested changes
I think some of the classes might be wrong

2022-01-04 17:56 UTC, nmalfroy commented on src/main/java/bio/terra/service/upgrade/Migrate.java
> +  private static final Logger logger = LoggerFactory.getLogger(UpgradeService.class);
Wouldn't this be the Migrate class?

2022-01-04 17:56 UTC, nmalfroy commented on src/main/java/bio/terra/service/dataset/flight/ingest/IngestCleanupStep.java
> +  private Logger logger = LoggerFactory.getLogger(DatasetIngestFlight.class);
Would this not be the IngestCleanupStep class?

2022-01-04 18:07 UTC, pshapiro4broad commented
I'm not a fan of everything (or most things) in Lombok, but its `@Log` annotation would avoid this boilerplate, and we wouldn't have to worry about making the `getLogger()` call match the class.  https://projectlombok.org/features/log

In DSP, the policy team is using this feature of Lombok in their project.

2022-01-04 18:32 UTC, snf2ye approved these changes

2022-01-04 21:18 UTC, fboulnois approved these changes

2022-01-05 16:03 UTC, nmalfroy approved these changes
thanks for making the changes!

2022-01-05 16:03 UTC, merged