add run reason and skip reason
DataBiosphere/jade-data-repo pull request #1203
Opened 2022-02-03 16:05 UTC by tcjiang9

2022-02-07 17:55 UTC, nmalfroy requested changes
Small things and I think the linting needs a pass

2022-02-07 17:55 UTC, nmalfroy commented on src/main/java/bio/terra/service/dataset/flight/ingest/CombinedFileIngestOptionalStep.java
> +    return numFiles + "bulk load files found to ingest";
you need an extra space here.  I'd recommend using string format. e.g.
```suggestion
    return String.format("%s bulk load file(s) found to ingest", numFiles);
```

2022-02-07 17:56 UTC, nmalfroy commented
Also, can you add the jira ticket to the PR?

2022-02-07 19:33 UTC, snf2ye approved these changes
Given @nmalfroy's comments are addressed, LGTM

2022-02-08 16:36 UTC, nmalfroy approved these changes

2022-02-08 16:37 UTC, merged