DR-2463 add validation for PKs and FKs
DataBiosphere/jade-data-repo pull request #1230
Opened 2022-03-09 20:31 UTC by tcjiang9

Primary keys and foreign keys when creating a dataset can't be arrays filerrefs or dirrefs

2022-03-09 21:44 UTC, nmalfroy approved these changes
looks great!

2022-03-10 14:53 UTC, tlangs requested changes

2022-03-10 14:53 UTC, tlangs commented on src/main/java/bio/terra/service/dataset/DatasetRequestValidator.java
> +
Most of this method is code duplication. I think it makes sense to pull the `errors.rejectValue` out into a helper method that can be shared between all three cases. Additionally, the number of `if` statements can be reduced by checking if the column data type exists in a set of invalid key types.

2022-03-14 18:22 UTC, snf2ye approved these changes

2022-04-01 20:22 UTC, snf2ye approved these changes

2022-04-04 18:50 UTC, tlangs approved these changes

2022-04-06 15:30 UTC, merged