Sl dc271 creat test dataset remove
DataBiosphere/jade-data-repo pull request #1249
Opened 2022-04-04 17:28 UTC by slucasbroad

Migrated the hca folder to data/catalog.

2022-04-04 20:25 UTC, fboulnois requested changes
There are merge conflicts you need to resolve before you can merge. My guess is that your branch was created from the develop branch without including the updates you made to the hca Python code. You should be able to resolve this by being on this branch and doing a git rebase: `git pull --rebase origin develop`

2022-04-05 01:32 UTC, fboulnois approved these changes
lgtm now

2022-04-05 15:47 UTC, pshapiro4broad approved these changes
Looks fine although I don't get why a commit on `develop` is showing up in this PR. It would be nice to have a "clean" PR before merging up.

2022-04-05 15:47 UTC, pshapiro4broad commented on .git-blame-ignore-revs
> +# To configure git to use this file when using `git blame`:
Any idea why this is showing up in the PR? I guess it couldn't hurt since it's the same content that's already on `develop`.

2022-04-05 17:07 UTC, merged