DR-2679 Register ingest service account in Terra when creating
DataBiosphere/jade-data-repo pull request #1326
Opened 2022-07-26 21:40 UTC by nmalfroy

This fixes the case where users want to ingest data from buckets in terra.  Before, there was really no way to allow a service account to read from terra controlled buckets if using a TDR created service account. This PR:
- Registers the service account in Terra
- Accepts the Terms of Service for that SA
- The integration tests that exercise creating an SA also call the admin api to delete the user from Sam to clean up (it's not in the client so I had to do direct REST calls)

2022-07-27 15:22 UTC, okotsopoulos requested changes
I found this easy to follow and well commented.  Thank you!

One open question around environment-specific settings but will approve once that's sorted.

2022-07-27 15:22 UTC, okotsopoulos commented on src/main/java/bio/terra/service/auth/iam/sam/SamIam.java
> +  static final String TOS_URL = "app.terra.bio/#terms-of-service";
Would we be able to use this as expected in Terra dev environment, this URL looks to be specific to prod?

2022-07-27 15:24 UTC, nmalfroy commented on src/main/java/bio/terra/service/auth/iam/sam/SamIam.java
> +  static final String TOS_URL = "app.terra.bio/#terms-of-service";
Ah you found that!  I actually tested and it's hard coded across envs in Sam so I left it as a constant

2022-07-28 14:46 UTC, okotsopoulos commented on src/main/java/bio/terra/service/auth/iam/sam/SamIam.java
> +  static final String TOS_URL = "app.terra.bio/#terms-of-service";
(We discussed during stand-up, closing the loop here for visibility) sounds good!  Would be great to have a comment here to avoid future confusion.

2022-07-28 14:46 UTC, okotsopoulos approved these changes

2022-07-28 20:45 UTC, samanehsan approved these changes
Lgtm!

2022-08-02 22:42 UTC, merged