[In Progress] DR-3420: Upgrade Postgres, Liquibase
DataBiosphere/jade-data-repo pull request #1567
Opened 2024-01-09 14:18 UTC by snf2ye

2024-01-18 16:35 UTC, nmalfroy requested changes
Thanks for doing this!  I think the middle commit can be a lot smaller if we just switch to use the apache commons lib

2024-01-18 16:35 UTC, nmalfroy commented on src/main/java/bio/terra/service/dataset/IngestRequestValidator.java
> +import liquibase.util.StringUtil;
Actually, maybe we should just switch this to be `org.apache.commons.lang3.StringUtils`. It seems like a mistake to use the liquidbase version of the utils

2024-01-18 16:46 UTC, snf2ye commented on src/main/java/bio/terra/service/dataset/IngestRequestValidator.java
> +import liquibase.util.StringUtil;
That is a great point; I'll switch it.

2024-01-18 18:18 UTC, s-rubenstein approved these changes

2024-01-22 16:45 UTC, nmalfroy approved these changes
thanks for making the updates!

2024-01-22 18:07 UTC, merged