DR 466 firestore project
DataBiosphere/jade-data-repo pull request #175
Opened 2019-07-19 19:56 UTC by tshahria

2019-07-24 22:40 UTC, thathert requested changes
A few things

2019-07-24 22:40 UTC, thathert commented on src/main/java/bio/terra/filesystem/FireStoreProject.java
> +            FireStoreProject fireStoreProject;
This can just be `FireStoreProject fireStoreProject = new FireStoreProject(projectId, credentials);`

2019-07-24 22:40 UTC, thathert commented on src/main/java/bio/terra/flight/dataset/create/CreateDatasetPrimaryDataStep.java
> +import bio.terra.metadata.*;
Can you expand this? We prefer to be explicit with imports and not use the `*`.

2019-07-24 22:40 UTC, thathert commented on src/main/java/bio/terra/flight/dataset/delete/DatasetDeleteFlight.java
> +        // Must delete primary data before metadata; it relies on being able to retrieveModel the
this should be `retrieve`, must have been a bad refactor

2019-07-24 22:40 UTC, thathert commented on src/test/java/bio/terra/dao/StudyDaoTest.java
> +        // so compare the id from the previous retrieveModel
All of these comments should be reverted

2019-07-24 22:40 UTC, thathert commented on src/test/java/bio/terra/integration/TestUtils.java
> +    private static org.slf4j.Logger logger = LoggerFactory.getLogger(TestUtils.class);
shouldn't be fully qualified

2019-07-24 22:40 UTC, thathert commented on src/test/java/bio/terra/integration/DataRepoClient.java
>              throw new IllegalStateException("unexpected interrupt waiting for response");
can you include `ex` as the second argument here (for the cause)?

2019-07-26 22:17 UTC, ddietterich approved these changes
I reviewed, made code changes based on my review, and now am approving. :)

2019-07-29 12:35 UTC, merged