first commit
DataBiosphere/jade-data-repo pull request #411
Opened 2020-03-11 14:55 UTC by smark88

2020-03-11 17:30 UTC, smark88 commented on .github/workflows/gradle-build-pr.yml
> +    if: "!contains(github.event.head_commit.message, 'ci skip')"
this doesn't work on PR nor does the previous syntax

2020-03-11 18:27 UTC, fboulnois requested changes
Should we create a GitHub Action template that both workflows can use? Otherwise, see other suggestions.

2020-03-11 18:27 UTC, fboulnois commented on .github/workflows/gradle-build-pr.yml
> +      - !.github/workflows/devimageupadte.yaml
also rename file

```suggestion
      - !.github/workflows/dev-image-update.yaml
```

2020-03-11 18:54 UTC, smark88 commented
> Should we create a GitHub Action template that both workflows can use? Otherwise, see other suggestions.

all jobs run on separate runners even if in the same yaml.

2020-03-11 19:13 UTC, smark88 commented on .github/workflows/gradle-build-pr.yml
> +    if: "!contains(github.event.head_commit.message, 'ci skip')"
found it 
```
if: "!contains( github.event.pull_request.labels.*.name, 'skip-ci')"
```

2020-03-12 12:21 UTC, thathert requested changes
It would be nice if we could DRY this up like @fboulnois suggests above.

2020-03-12 12:21 UTC, thathert commented on .github/workflows/dev-image-update.yaml
> +          git config --global user.name "smark88"
Can we switch this to something like robot@jade.team and robot?

2020-03-12 14:07 UTC, smark88 commented on .github/workflows/dev-image-update.yaml
> +          git config --global user.name "smark88"
It's tied to a personal developer key will that work ?

2020-03-12 14:23 UTC, smark88 commented
> It would be nice if we could DRY this up like @fboulnois suggests above.

I don't where to template in 

> It would be nice if we could DRY this up like @fboulnois suggests above.

I dont know where to template or dry in .github/workflows/dev-image-update.yaml

2020-03-13 13:35 UTC, thathert approved these changes
LGTM

2020-03-13 14:16 UTC, merged

2020-03-13 15:04 UTC, fboulnois requested changes
nvm