DR-120: validate dataset
DataBiosphere/jade-data-repo pull request #48
Opened 2019-02-19 22:50 UTC by RoriCremer

2019-02-20 22:16 UTC, ahaessly approved these changes
👍

2019-02-21 02:10 UTC, thathert requested changes
Looks good. One small change around the description validation (we'll want to use it for the study description too).

2019-02-21 02:10 UTC, thathert commented on src/main/java/bio/terra/validation/DatasetRequestValidator.java
> +        } else if (description.length() > 2048) {
Let's move this into `ValidationUtils`

2019-02-21 20:47 UTC, thathert approved these changes

2019-02-21 20:47 UTC, merged