rough python script to create subsets of ENCODE data for testing
DataBiosphere/jade-data-repo pull request #5
Opened 2018-11-28 23:16 UTC by RoriCremer

This can get cleaned up substantially--just wanted to get it on github

2018-11-30 19:01 UTC, ddietterich reviewed
A few code comments - basically observations of possible improvements. Nothing required.

What I'd like to understand before approving is why we would store the json data files that are the outputs of running to tools.

Do we have access to the files that are referred to by this data?

2018-11-30 19:01 UTC, ddietterich commented on src/test/resources/encode-test-data-subset.py
> +donorRows = dataDonors.readlines()
Is there a way to read the JSON file as JSON, instead of processing it as text?
That would make the data references more meaningful (instead of [20: 31]).

2018-11-30 19:01 UTC, ddietterich commented on src/test/resources/encode-test-data-subset.py
> +    dataFiles = open('encode-data-files.json')
Also, reading as JSON would let you open, read and parse the JSON file once and re-search the memory image, instead of opening/closing each time.

2018-11-30 19:01 UTC, ddietterich commented on src/test/resources/encode-test-data-subset.py
> +    testDataDonors.write(testDonor)
Does this mean you will write blank lines into testDataDonors when there are too many files? Is it worth filtering out the not founds?

2018-12-03 18:16 UTC, thathert requested changes
Dan made some good comments here about the approach; Parsing JSON and dealing with the object representation is ideal compared to working line-by-line in the file. I think good feedback for the next time we do something similar, but not necessary to change in this PR. 

I would like for us to remove the JSON files that are part of this PR. We have the source files in a google bucket and the output files there as well. Can we just include the location of the bucket here in a comment somewhere?

2018-12-05 21:06 UTC, thathert approved these changes

2018-12-05 21:06 UTC, merged