testing cleanup no tix
DataBiosphere/jade-data-repo pull request #50
Opened 2019-02-20 15:47 UTC by RoriCremer

2019-02-21 02:36 UTC, thathert requested changes
Looks good, one comment about adding StudyFixtures

2019-02-21 02:36 UTC, thathert commented on src/test/java/bio/terra/fixtures/FlightStates.java
> +// CHECKSTYLE:OFF
How come?

2019-02-21 02:36 UTC, thathert commented on src/test/java/bio/terra/fixtures/FlightStates.java
> +    public static final StudySummaryModel studySummary = new StudySummaryModel()
It'd be useful to have a `StudyFixtures` class alongside this one that can generate Study summaries and Study request models.

2019-02-21 02:36 UTC, thathert commented on src/test/java/bio/terra/fixtures/FlightStates.java
> +    public static final StudySummaryModel minimalStudySummary = new StudySummaryModel()
I think both of these can be removed and we can use `StudyFixtures.makeStudySummary()` in the the methods below.

2019-02-22 16:47 UTC, thathert approved these changes
LGTM

2019-02-22 16:57 UTC, ahaessly approved these changes
just one q

2019-02-22 16:57 UTC, ahaessly commented on src/test/java/bio/terra/fixtures/FlightStates.java
> +    public static final String submittedTimeFormatted = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS")
is this supposed to be testing the date format? if not, should you use
    @Autowired
    private SimpleDateFormat modelDateFormat;

2019-02-22 17:02 UTC, merged