DR-144: move root column field to asset spec
DataBiosphere/jade-data-repo pull request #51
Opened 2019-02-20 22:30 UTC by ahaessly

2019-02-21 12:31 UTC, thathert requested changes
Looks good, a couple things requested.

2019-02-21 12:31 UTC, thathert commented on src/main/java/bio/terra/model/StudyJsonConversion.java
> +                    .collect(Collectors.toMap(colName -> colName, colName ->
👍 This pattern with `Collectors.toMap` is really cool

2019-02-21 12:31 UTC, thathert commented on src/main/java/bio/terra/validation/StudyRequestValidator.java
> +    private boolean validateAssetTable(
nit: Can we update this name to something like `validateAssetTableAndCheckRoot` to distinguish between this and the other void validate methods?

2019-02-21 12:31 UTC, thathert commented on src/test/java/bio/terra/controller/StudyTest.java
Can you add a test to catch the missing root column case?

2019-02-22 14:37 UTC, RoriCremer approved these changes

2019-02-22 16:37 UTC, thathert approved these changes

2019-02-22 16:37 UTC, merged