literally just a typo in sample study
DataBiosphere/jade-data-repo pull request #70
Opened 2019-03-12 14:34 UTC by RoriCremer

2019-03-12 16:52 UTC, thathert submitted a review, later dismissed

2019-03-12 17:22 UTC, ddietterich requested changes
Fixing that typo has consequences

2019-03-12 17:22 UTC, ddietterich commented on src/test/resources/study-minimal.json
> +        "name":   "sample",
That will break my dataset connected tests.
So either don't do this or make the corresponding change to the dataset test.

2019-03-21 16:19 UTC, thathert approved these changes
LGTM

2019-03-22 18:23 UTC, ddietterich approved these changes
Think you caught them all. Thanks!

2019-03-22 22:03 UTC, merged